name: Sync to GitHub Pages

on:
  push:
    branches:
      - main
    paths:
      - 'posts/**'  # Only trigger when posts are updated

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout lab journal
        uses: actions/checkout@v3
        with:
          path: lab-journal
      
      - name: Checkout GitHub Pages repository
        uses: actions/checkout@v3
        with:
          repository: prashantbhaga/prashantbhaga.github.io
          token: ${{ secrets.CONTENT_SYNC_TOKEN }}
          path: github-pages
      
      - name: Set up date directories
        run: |
          # Create _posts directory if it doesn't exist
          mkdir -p github-pages/_posts
      
      - name: Format and sync posts
        run: |
          for file in lab-journal/posts/*.md; do
            if [ -f "$file" ]; then
              filename=$(basename "$file")
              jekyll_filename="$(date +%Y-%m-%d)-$filename"
              
              # Check if the file already exists
              if [ -f "github-pages/_posts/$jekyll_filename" ]; then
                echo "$jekyll_filename already exists. Skipping."
              else
                echo "Processing $filename"
                
                # Add front matter if not already present
                if ! grep -q "^---" "$file"; then
                  tempfile=$(mktemp)
                  echo "---" > "$tempfile"
                  echo "layout: post" >> "$tempfile"
                  echo "title: \"$(basename "$file" .md)\"" >> "$tempfile"
                  echo "date: $(date -u "+%Y-%m-%d %H:%M:%S %z")" >> "$tempfile"
                  echo "categories: lab-notes" >> "$tempfile"
                  echo "---" >> "$tempfile"
                  cat "$file" >> "$tempfile"
                  cp "$tempfile" "$file"
                  rm "$tempfile"
                fi
                
                # Copy new post
                cp "$file" "github-pages/_posts/$jekyll_filename"
                echo "Synced $jekyll_filename"
              fi
            fi
          done
      
      - name: Commit and push changes
        run: |
          cd github-pages
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git diff --quiet && git diff --staged --quiet || git commit -m "Sync lab journal posts $(date +%Y%m%d%H%M%S)"
          git push


# I added a check to see if a post with the same filename already exists in the target repo. If it does, the script skips that file, preventing duplication. Let me know if you’d like me to refine it further or add extra functionality! 🚀
